### ISSUE TITLE
Consider more dynamic light/dark mode handling

### ISSUE THREAD

**Issue by AttemptToCallNil** [MediaWikiAGE/MAGE#61]
Currently using light or dark mode is determined once, when MAGE starts up. It's also hard-bound to the light/dark setting of the OS. I'm not sure this is even possible, but if it is, a more advanced approach might have some advantages. Defaulting to the OS mode with the ability to switch modes at runtime will let people specifically use a mode not configured for their OS (in case they have MAGE-specific mode preferences), but (arguably, more importantly) this could seriously simplify light/dark mode testing for developers. Right now I'd have to close MAGE and re-run `pnpm run electron:serve` whenever I want to test MAGE with a different mode.

**Comment by Helcostr** [comment]
https://github.com/justjavac/is-dark-theme

**Comment by AttemptToCallNil** [comment]
Hm, yeah, that might work
