### ISSUE TITLE
Wikis on the same domain with not-Fandom-like different paths don't get saved correctly

### ISSUE THREAD

**Issue by AttemptToCallNil** [MediaWikiAGE/MAGE#67]
Try saving a "wiki farm" with these wikis:
```
https://cat.cat/Main Page
https://cat.cat/de/Main Page
https://cat.cat/ru/Main Page
```
The current "get-wikiname-from-url" algorithm assumes that wiki farms either use separate subdomains, or Fandom-like paths that start with `/[two letters]/wiki`. In other cases (same domain, other kind of paths), the login form will only save the last entry and overwrite the rest with it.

I don't think there can be a universal conflict resolution algorithm for this problem, so I guess adding indices like `cat.cat [2]`, `cat.cat [3]` is the way to go, at least for now.

**Comment by Helcostr** [comment]
Uh oh XD

**Comment by AttemptToCallNil** [comment]
I already fixed this issue in my coming PR.
