### ISSUE TITLE
Issue with Footer.vue after latest dependency update

### ISSUE THREAD

**Issue by TreeIsLife2** [MediaWikiAGE/MAGE#75]
Error looks like:

```
ERROR in
(path to MAGE's location)\MAGE\src\components\Footer.vue
  1:1  error  Component name "Footer" should always be multi-word  vue/multi-word-component-names
```

**Comment by AttemptToCallNil** [comment]
Yes, that's one of the changed lints. Strangely enough, this specific component was not giving me errors when I was testing the update. I also can't reproduce the issue by running `pnpm run electron:serve` (which made the errors with other components appear), but I do believe this issue is valid.

**Comment by AttemptToCallNil** [comment]
Does #76 resolve this issue?

**Comment by TreeIsLife2** [comment]
Yes, it does.

**Comment by AttemptToCallNil** [comment]
As #76 is now merged, I'm closing this issue.
